xp = get(logsout, 'xp'); % derivative of the plant state vector
x  = get(logsout, 'x'); % plant state vector
e  = get(logsout, 'e'); % state error vector
dp = get(logsout, 'dp'); % process disturbance
do = get(logsout, 'do'); % output disturbance
w = get(logsout, 'w'); % measurement noise
y = get(logsout, 'y'); % quantized and sampled output with noise
y_star = get(logsout, 'y*'); % sampled output with noise and disturbance
y_dstar = get(logsout, 'y**'); % output with noise and disturbance
y_tstar = get(logsout, 'y***'); % output with disturbance
y_qstar = get(logsout, 'y****'); % clear output
u = get(logsout, 'u'); % control signal
u_star = get(logsout, 'u*'); % control signal before dead time
refSig = get(logsout, 'refSig'); % reference signal
refSigDerivative = get(logsout, 'refSigDerivative'); % reference signal
refSigSecondDerivative = get(logsout, 'refSigSecondDerivative'); % reference signal
refSigThirdDerivative = get(logsout, 'refSigThirdDerivative'); % reference signal
z_hat = get(logsout, 'z_hat'); % estimated extended state
